### ISSUE TITLE
What is the version of mmcv you used?

### ISSUE THREAD

**Issue by luoyixin2019** [caiqi/sample-weighting-network#2]
It is a nice work!
I would like to ask you what is the version of mmcv you used?
Cause I got the error when run your train code.

**Comment by caiqi** [comment]
I used mmcv of version 0.2.14. For newer versions of mmcv, you may need to make some modifications: https://github.com/open-mmlab/mmdetection/issues/1862#issuecomment-598173008 
```
pip install mmcv==0.2.14
```
should work.
